#!/bin/bash
rm /etc/localtime && ln -s /usr/share/zoneinfo/America/Sao_Paulo /etc/localtime
apt-get update
#apt-get upgrade -y
apt-get install curl -y
apt-get install apache2 -y
apt-get install php5 libapache2-mod-php5 php5-mcrypt -y
apt-get install mysql-server -y
#mysql_install_db
mysql_secure_installation
apt-get install phpmyadmin -y
php5enmod mcrypt
service apache2 restart
ln -s /usr/share/phpmyadmin /var/www/html/phpmyadmin
apt-get install libssh2-1-dev libssh2-php -y
php -m |grep ssh2
cd 
apt-get install unzip
wget https://github.com/matheuslarcher20/Painel_install/raw/master/app.zip
mv php.zip /var/www/html/
cd /var/www/html
unzip php.zip
rm php.zip
IP=$(wget -qO- ipv4.icanhazip.com)
read -p "Senha para mysql e Banco de dados: " SENHA
mysql -h localhost -u root -p$SENHA -e "CREATE DATABASE ssh"
service apache2 restart

rm -rf Painel_Install.sh

echo "Port 22
Protocol 2
KeyRegenerationInterval 3600
ServerKeyBits 1024
SyslogFacility AUTH
LogLevel INFO
LoginGraceTime 120
PermitRootLogin yes
StrictModes yes
RSAAuthentication yes
PubkeyAuthentication yes
IgnoreRhosts yes
RhostsRSAAuthentication no
HostbasedAuthentication no
PermitEmptyPasswords no
ChallengeResponseAuthentication no
PasswordAuthentication yes
X11Forwarding yes
X11DisplayOffset 10
PrintMotd no
PrintLastLog yes
TCPKeepAlive yes
#UseLogin no
AcceptEnv LANG LC_*
Subsystem sftp /usr/lib/openssh/sftp-server
UsePAM yes" > /etc/ssh/sshd_config
service ssh restart
echo -e "\033[05;32mInstalação concluida!!\033[0m"

clear
echo "
 1 - abra o arquivo pass.php e digite sua senha. Ex: <?php $pass = 'SUA_SENHA';?> 
nano /var/www/html/pages/system/pass.php"
echo "
2 - Acesse: $IP/phpmyadmin E crie um Banco de Dados SSH
 
 
    ******Final*******"
 
