#!/bin/bash
nomecoment=$(echo VIVO)
newclient () {
        # Generates the custom client.ovpn
        cp /etc/openvpn/client-common.txt ~/$nomecoment.ovpn
        echo "<ca>" >> ~/$nomecoment.ovpn
        cat /etc/openvpn/easy-rsa/pki/ca.crt >> ~/$nomecoment.ovpn
        echo "</ca>" >> ~/$nomecoment.ovpn
        echo "<cert>" >> ~/$nomecoment.ovpn
        cat /etc/openvpn/easy-rsa/pki/issued/.crt >> ~/$nomecoment.ovpn
        echo "</cert>" >> ~/$nomecoment.ovpn
        echo "<key>" >> ~/$nomecoment.ovpn
        cat /etc/openvpn/easy-rsa/pki/private/.key >> ~/$nomecoment.ovpn
        echo "</key>" >> ~/$nomecoment.ovpn
        echo "<tls-auth>" >> ~/$nomecoment.ovpn
        cat /etc/openvpn/ta.key >> ~/$nomecoment.ovpn
        echo "</tls-auth>" >> ~/$nomecoment.ovpn
}


                       ./easyrsa build-client-full $nomecoment nopass
                        # Generates the custom client.ovpn
                        newclient "$nomecoment"
                        VALIDADOR=$(cat /etc/openvpn/easy-rsa/pki/issued/$nomecoment.crt)
IP=$(wget -qO- ipv4.icanhazip.com)
                        if [[ $VALIDADOR = "" ]]; then
                        echo -e "
\033[0;31m Erro ao gerar certificado para: $nomecoment.$IP.ovpn !!\033[0m"
else
cd
mv $nomecoment.ovpn $nomecoment.$IP.ovpn
                        echo " "
                        echo -e "\033[1;36m Novo certificado foi gerado para: \033[1;37m$IP\033[0m"
                        echo " "
                        echo -e "\033[1;36m Seu arquivo está disponivel em \033[1;37m /root/$nomecoment.ovpn\033[0m"
                     fi
exit
